controllers:
    resource: '../../Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

workerpayment.api:
    resource: '../var/plugins/WorkerPayment/API/'
    type: rest
    prefix: /api
