services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\WorkerPayment\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\WorkerPayment\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
